# Generated by Django 3.0.7 on 2021-05-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm1', '0005_customer_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='profile_picture',
            field=models.ImageField(blank=True, default='Arpit.png', null=True, upload_to=''),
        ),
    ]
